# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RxNetworkExt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxNetworkExt
  pod 'Moya/RxSwift'
  pod 'Cache'
  pod 'CleanJSON'
  pod 'NSObject+Rx'
  

end
